version: '3'

services:
  mail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postfix-mail
    ports:
      - 25:25
    environment:
      KEY: Value
    volumes:
      - ./mail:/var/spool/mail