version: '3'

services:
  mail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postfix-mail
    ports:
      - 25:25
    environment:
      MY_DOMAIN: localhost # mydomain.com
    volumes:
      - ./mail:/var/spool/mail
      - /etc/letsencrypt/live/:/run/ssl/